// frontend/src/lib/components/spotify/PlaylistPreview.tsx
import { Link } from 'react-router-dom'

type Playlist = SpotifyApi.PlaylistObjectSimplified

interface PlaylistPreviewProps {
	playlist?: Playlist
	link?: (playlist: Playlist) => string
}

const defaultLink = (playlist: Playlist) => `${location.pathname}/playlist?id=${playlist.id}`

function getPhoto(images: SpotifyApi.ImageObject[]) {
	if (images.length == 1)
		return images[0].url // 640x640
	else return images[1].url // 300x300
}

export function PlaylistPreview({ playlist, link = defaultLink }: PlaylistPreviewProps) {
	const className = `grid bg-[#0000001a] rounded-sm h-20 items-center${
		playlist ? '' : ' loading'
	}`
	const style = { gridTemplateColumns: '80px auto' }

	const content = (
		<>
			<div className="playlistImage">
				{playlist && (
					<img
						src={getPhoto(playlist.images)}
						alt={`"${playlist.name}" playlist cover`}
						height="80"
						width="80"
						className="object-cover rounded-l-sm"
					/>
				)}
			</div>
			<div>
				<p className="px-4 mb-0 text-left">{playlist?.name ?? ''}</p>
			</div>
		</>
	)

	// Skeleton placeholders had no href, so they stay inert anchors.
	if (!playlist) {
		return (
			<a className={className} style={style}>
				{content}
			</a>
		)
	}
	return (
		<Link to={link(playlist)} className={className} style={style}>
			{content}
		</Link>
	)
}

// src/lib/components/spotify/PlaylistPreview.svelte
<script lang="ts">
	/* eslint-disable no-undef */
	export let playlist: SpotifyApi.PlaylistObjectSimplified | undefined = undefined
	export let link = (playlist: SpotifyApi.PlaylistObjectSimplified) =>
		location.pathname + '/playlist?id=' + playlist.id

	function getPhoto(images: SpotifyApi.ImageObject[]) {
		if (images.length == 1) return images[0].url // 640x640
		else return images[1].url // 300x300
	}
	/*  eslint-enable no-undef */
</script>

<a
	href={playlist ? link(playlist) : undefined}
	class:loading={!playlist}
	class="grid bg-[#0000001a] rounded h-20 items-center"
	style="grid-template-columns: 80px auto;"
>
	<div class="playlistImage" class:w-30={playlist}>
		{#if playlist}
			<img
				src={getPhoto(playlist.images)}
				alt={`"${playlist.name}" playlist cover`}
				height="80"
				width="80"
				class="object-cover rounded-l"
			/>
		{/if}
	</div>
	<div class="">
		<p class="px-4 mb-0 text-left">{playlist?.name ?? ''}</p>
	</div>
</a>
