// frontend/src/lib/components/AuthSpotify.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import { createTokenStore } from '$lib/stores'
	import AuthSpotifyButton from './AuthSpotifyButton.svelte'

	export let scopes: string | undefined = undefined
	export let path: string
	let token = createTokenStore(path)

	onMount(() => {
		token.check()
	})
</script>

{#if $token === undefined}
	<!-- loading state -->
{:else if $token == null}
	<AuthSpotifyButton authType="token" {scopes} />
{:else}
	<slot token={`${$token}`} />
{/if}

// frontend/src/lib/components/AuthSpotify.tsx
import type { ReactNode } from 'react'
import { useSpotifyToken } from '@/hooks/useSpotifyToken'
import { AuthSpotifyButton } from './AuthSpotifyButton'

interface AuthSpotifyProps {
	path: string
	scopes?: string
	/** Render prop, replacing Svelte's `<slot token={...}>` / `let:token`. */
	children: (token: string) => ReactNode
}

export function AuthSpotify({ path, scopes, children }: AuthSpotifyProps) {
	const token = useSpotifyToken(path)

	if (token === null) return <AuthSpotifyButton authType="token" scopes={scopes} />
	return <>{children(token)}</>
}
