// frontend/src/lib/components/AuthFirebase.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import { user } from '$lib/stores'

	let url: string

	onMount(() => {
		url = '/login?redirect=' + encodeURIComponent(location.pathname)
	})
</script>

{#if $user === undefined}
	<!-- loading state -->
{:else if $user == null}
	<a href={url} class="btn-primary">Login</a>
	<p class="mt-4">Log in to use our tools</p>
{:else}
	<slot />
{/if}

// frontend/src/lib/components/AuthFirebase.tsx
import type { ReactNode } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { useUser } from '@/lib/contexts/user'

export function AuthFirebase({ children }: { children: ReactNode }) {
	const user = useUser()
	const { pathname } = useLocation()

	if (user === undefined) return null // still resolving auth state
	if (user === null) {
		return (
			<>
				<Link
					to={`/login?redirect=${encodeURIComponent(pathname)}`}
					className="btn-primary"
				>
					Login
				</Link>
				<p className="mt-4">Log in to use our tools</p>
			</>
		)
	}
	return <>{children}</>
}
